### ISSUE TITLE
Does not re-compute positions of sections when viewport height changes

### ISSUE THREAD

**Issue by kyleoliveiro** [stormid/storm-scroll-spy#3]

**Comment by kyleoliveiro** [comment]
Sorry for the vague description.

In my case, I had "tabs" within the sections in my page. When switching through the tabs, the tab panel height would change due to differing content lengths. This also caused the height of the sections to change, without the viewport being resized. The changes to the height of the sections in this manner were not registered by storm-scroll-spy.

I made the necessary patches for my case in https://github.com/kyleoliveiro/storm-scroll-spy.

**Comment by mjbp** [comment]
No problem, thanks for taking the time to explain and sorry for my slow response.

I see what you mean, I agree it's a legit issue. As for the solution, I'm reluctant to add call setPositions in setCurrentItem, setPositions is a reflow-triggering function.

As an alternative I've added a mutationobserver to look out for attribute changes anywhere in the document.body then call setPositions. Let me know what you think.

**Comment by kyleoliveiro** [comment]
Yes,  mutationobserver is the ideal solution IMO. Mine was a hotfix.

**Comment by mjbp** [comment]
Grand. Thanks for your help on this one.
